// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"
)

type Pembelian struct {
	ID          int32          `json:"id"`
	UserID      sql.NullInt32  `json:"user_id"`
	NamaBarang  sql.NullString `json:"nama_barang"`
	HargaBarang sql.NullInt32  `json:"harga_barang"`
	Status      sql.NullString `json:"status"`
	CreatedAt   time.Time      `json:"created_at"`
}

type Penjualan struct {
	ID          int32          `json:"id"`
	UserID      sql.NullInt32  `json:"user_id"`
	BeratSampah sql.NullInt32  `json:"berat_sampah"`
	JenisSampah sql.NullString `json:"jenis_sampah"`
	HargaSampah sql.NullInt32  `json:"harga_sampah"`
	Status      sql.NullString `json:"status"`
	Keuntungan  sql.NullInt32  `json:"keuntungan"`
	CreatedAt   time.Time      `json:"created_at"`
}

type RiwayatPembelian struct {
	ID          int32         `json:"id"`
	UserID      sql.NullInt32 `json:"user_id"`
	PembelianID sql.NullInt32 `json:"pembelian_id"`
	CreatedAt   time.Time     `json:"created_at"`
}

type RiwayatPenjualan struct {
	ID          int32         `json:"id"`
	UserID      sql.NullInt32 `json:"user_id"`
	PenjualanID sql.NullInt32 `json:"penjualan_id"`
	CreatedAt   time.Time     `json:"created_at"`
}

type User struct {
	ID          int32          `json:"id"`
	Photo       sql.NullString `json:"photo"`
	Username    sql.NullString `json:"username"`
	Password    sql.NullString `json:"password"`
	NoHp        sql.NullString `json:"no_hp"`
	Email       sql.NullString `json:"email"`
	Saldo       sql.NullInt32  `json:"saldo"`
	TotalSampah sql.NullInt32  `json:"total_sampah"`
	Role        sql.NullString `json:"role"`
	CreatedAt   time.Time      `json:"created_at"`
}
