// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"
)

type Pembelian struct {
	ID          int32         `json:"id"`
	UserID      sql.NullInt32 `json:"user_id"`
	NamaBarang  string        `json:"nama_barang"`
	HargaBarang int32         `json:"harga_barang"`
	Status      string        `json:"status"`
	CreatedAt   time.Time     `json:"created_at"`
}

type Penjualan struct {
	ID          int32         `json:"id"`
	UserID      sql.NullInt32 `json:"user_id"`
	BeratSampah int32         `json:"berat_sampah"`
	JenisSampah string        `json:"jenis_sampah"`
	HargaSampah int32         `json:"harga_sampah"`
	Status      string        `json:"status"`
	Keuntungan  int32         `json:"keuntungan"`
	CreatedAt   time.Time     `json:"created_at"`
}

type RiwayatPembelian struct {
	ID          int32         `json:"id"`
	UserID      sql.NullInt32 `json:"user_id"`
	PembelianID sql.NullInt32 `json:"pembelian_id"`
	CreatedAt   time.Time     `json:"created_at"`
}

type RiwayatPenjualan struct {
	ID          int32         `json:"id"`
	UserID      sql.NullInt32 `json:"user_id"`
	PenjualanID sql.NullInt32 `json:"penjualan_id"`
	CreatedAt   time.Time     `json:"created_at"`
}

type User struct {
	ID          int32          `json:"id"`
	Photo       sql.NullString `json:"photo"`
	Username    string         `json:"username"`
	Password    string         `json:"password"`
	NoHp        sql.NullString `json:"no_hp"`
	Email       sql.NullString `json:"email"`
	Saldo       int32          `json:"saldo"`
	TotalSampah int32          `json:"total_sampah"`
	Role        string         `json:"role"`
	CreatedAt   time.Time      `json:"created_at"`
}
