// Code generated by sqlc. DO NOT EDIT.
// source: pembelian.sql

package db

import (
	"context"
)

const createPembelian = `-- name: CreatePembelian :exec
INSERT INTO pembelian (
  nama_barang, harga_barang
) VALUES (
  ?, ?
)
`

type CreatePembelianParams struct {
	NamaBarang  string `json:"nama_barang"`
	HargaBarang int32  `json:"harga_barang"`
}

func (q *Queries) CreatePembelian(ctx context.Context, arg CreatePembelianParams) error {
	_, err := q.db.ExecContext(ctx, createPembelian, arg.NamaBarang, arg.HargaBarang)
	return err
}

const updateStatusPembelian = `-- name: UpdateStatusPembelian :exec
UPDATE pembelian SET status = ? WHERE user_id = ?
`

type UpdateStatusPembelianParams struct {
	Status string        `json:"status"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) UpdateStatusPembelian(ctx context.Context, arg UpdateStatusPembelianParams) error {
	_, err := q.db.ExecContext(ctx, updateStatusPembelian, arg.Status, arg.UserID)
	return err
}
