// Code generated by sqlc. DO NOT EDIT.
// source: penjualan.sql

package db

import (
	"context"
)

const createPenjualan = `-- name: CreatePenjualan :exec
INSERT INTO penjualan (
  berat_sampah, jenis_sampah, harga_sampah, keuntungan
) VALUES (
  ?, ?,? ,?
)
`

type CreatePenjualanParams struct {
	BeratSampah int32  `json:"berat_sampah"`
	JenisSampah string `json:"jenis_sampah"`
	HargaSampah int32  `json:"harga_sampah"`
	Keuntungan  int32  `json:"keuntungan"`
}

func (q *Queries) CreatePenjualan(ctx context.Context, arg CreatePenjualanParams) error {
	_, err := q.db.ExecContext(ctx, createPenjualan,
		arg.BeratSampah,
		arg.JenisSampah,
		arg.HargaSampah,
		arg.Keuntungan,
	)
	return err
}

const updateStatusPenjualan = `-- name: UpdateStatusPenjualan :exec
UPDATE penjualan SET status = ? WHERE user_id = ?
`

type UpdateStatusPenjualanParams struct {
	Status string        `json:"status"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) UpdateStatusPenjualan(ctx context.Context, arg UpdateStatusPenjualanParams) error {
	_, err := q.db.ExecContext(ctx, updateStatusPenjualan, arg.Status, arg.UserID)
	return err
}
